### ISSUE TITLE
Not ready to be used as a (static) library in projects

### ISSUE THREAD

**Issue by mikekaganski** [achan001/dtoa-fast#1]
Hi!

It would be nice if this nice project would be shaped in a way to be usable as a static library in other projects. Specifically, some makefiles included for some platforms/compilers (as a starting point); simple directory structure added; and a release be prepared with corresponding tarball. That would enable to reference the tarball to be downloaded and compiled wherever needed?

(I'm looking at a possibility to use it in LibreOffice, and seeing a sample makefile here would allow me to try and come back with whatever improvements we could create downstream; but the task to create this from scratch and keep a LO-own hosted tarball, without knowing that our changes would be accepted upstream, would mean supporting our own fork, which is not good for us.)

Thank you very much for this piece of software!

**Comment by achan001** [comment]
Thanks for the compliment :-)

I am not sure it is worth the work to make a library out of so few functions.
Also, a static library meant we have to lock-in some #defines, losing flexibility.

Example, below is a makefile, assuming FE_TONEAREST, and not using FAST_BF96
(FAST_BF96 does the scaling in 1 step, instead of upto 8, at the cost of a 8k lookup table)
```
CC = gcc -Wall -std=gnu99
CFLAGS = -c -O2 -Id:/cpp -Ic:/ $(ARG)
LIB = libdtoafast.a
DEL = rm -f

all:            $(LIB)
clean:; @$(DEL) *.o

OBJS = dtoa-fast.o dtoa-ifmt1.o

$(LIB): $(OBJS)
        $(DEL) $(LIB)
        ar rc $(LIB) $(OBJS)

# Assumed FE_TONEAREST, GMP for ULP tie-breaker
dtoa-fast.o: dtoa-fast.c dtoa-aux.c strtod-fast.c strtod-aux.c strtod-gmp.c
        $(CC) $(CFLAGS) -DUSE_MAPM=0 dtoa-fast.c

# DTOA_IFMT_G defined: 1.0 -> "1.0"
dtoa-ifmt1.o: dtoa-ifmt1.c
        $(CC) $(CFLAGS) -DDTOA_IFMT_G dtoa-ifmt1.c
```

**Comment by achan001** [comment]
This showed makefile work as expected
```
d:\cpp\dtoa> make
gcc -Wall -std=gnu99 -c -O2 -Id:/cpp -Ic:/  -DUSE_MAPM=0 dtoa-fast.c
gcc -Wall -std=gnu99 -c -O2 -Id:/cpp -Ic:/  -DDTOA_IFMT_G dtoa-ifmt1.c
rm -f libdtoafast.a
ar rc libdtoafast.a dtoa-fast.o dtoa-ifmt1.o
```
And, to test the static library, using 2 examples from dtoa-fast.txt
```
d:\cpp\dtoa> run igcc.py -Ic:\mapm -idtoa-fast.h -L. -ldtoafast -lgmp-10

gcc:1> double x; char *s; int sgn, len, dec
gcc:2> x = strtod_fast("4.3915445623487279e17", NULL)
gcc:3> s = dtoa_fast(x, 0, &sgn, &len, &dec)
gcc:4> puts(dtoa_ifmt(s, sgn, len, dec, 'g'))
439154456234872770.0

gcc:5> s = dtoa_fast(x, 10, &sgn, &len, &dec)
gcc:6> puts(dtoa_ifmt(s, sgn, len, dec, 'g'))
4.391544562e+017

gcc:7> x = strtod_fast("4.502463450621225E-321", NULL)
gcc:8> s = dtoa_fast(x, 0, &sgn, &len, &dec)
gcc:9> puts(dtoa_ifmt(s, sgn, len, dec, 'g'))
4.5e-321
```
Both results, behind the scene
```
"4.3915445623487279e17"
0x0.9c04dd78,8a7b2f00,00000000p+56      mantissa only
0x0.c30614d6,ad19fac0,00000000p+59      scaled binary
        round down
0x0.c30614d6,ad19f800,00000000p+59      rounded double
0x0.9c04dd78,8a7b2ccc,cccccccbp+56      mantissa only

mantissa => 43915445623487276 + 0.79999999999836291
safe ulp => 3.1999999998137358
safe = 43915445623487274 to 43915445623487279

edge = .4391544562348728E18             unable to round-trip
0x0.f9a1625a,772b8000,00000000p+52      mantissa only
0x0.c30614d6,ad19fc00,00000000p+59      scaled binary

best = 43915445623487277
+0x1.860c29ad5a33fp+58 = +4.3915445623487277e17
```
```
"4.502463450621225E-321"
0x0.ffef7769,6a529000,00000000p+52      mantissa only
0x0.e3d3c286,4c639dbc,50b85aa6p-1064    scaled binary
0x0.00000000,001c7a78,50c98c73p-1021    fix subnormal
        round down
0x0.e3c00000,00000000,00000000p-1064    rounded double
0x0.9fe7cafe,7ef5582c,ab1387c1p+56      mantissa only

mantissa => 4500 + 0.93803361375601735
safe ulp => 2.4703282290624431
safe = 4499 to 4503
best = 45
+0x0.000000000038fp-1022 = +4.5e-321
```

**Comment by mikekaganski** [comment]
> Thanks for the compliment :-)

This is well-deserved. You had put your expertise in it, to create great functions!

> I am not sure it is worth the work to make a library out of so few functions.

It does worth it. Suppose someone wants to use it; one may take your code directly, and use in one's projects by copy-pasting, and then one would need to check from time to time if there's an update here addressing some issue, or improving something maybe (e.g., increasing performance even more); then copy and paste the code into own project, hoping that the building assumptions still hold, and having to figure what had changed. Or one could reference the library tarball from one's in their projects, and have its up-to-date code on builds just by referencing a newer tarball which has the build logic in a black box. Take into account that the functions, although "few", include a difficult-to-understand math, that not everyone could support in their projects by themselves.

> Also, a static library meant we have to lock-in some #defines, losing flexibility.

No. The makefiles could (must!) take passed arguments into account, thus relying on user passing correct arguments. The makefiles should check the passed arguments (environment variables), and if the defines are missing, then assume some defaults, but otherwise use the passed values.

> Example, below is a makefile, assuming FE_TONEAREST, and not using FAST_BF96
> (FAST_BF96 does the scaling in 1 step, instead of upto 8, at the cost of a 8k lookup table)

Thank you! This partially answers to my doubt (I always doubted if FAST_BF96 only sacrifices code size, and not accuracy of the result; if it actually means the fastest possible code at the cost of the size, and without any inaccuracies introduced). If using FAST_BF96 is the fastest, in my use case, I would be using the fastest mode (the 8K table doesn't matter here), in no-GPL mode (LibreOffice use MPLv2, so we can't incorporate GPL code).

Note that it's important that the project has some *releases* (e.g. v.0.0.1) with source tarballs, so that the tarball could be referenced using its URL for using in the project; it could be downloaded, extracted using `tar`; and then the correct project structure would appear - with subdirectories that could be passed to main program as include/lib directories, etc. Currently, if I e.g. use the "tarball" (ZIP) offered by github for a revision, I only have a flat structure after untaring it (even though the ZIP seems to contain a subdirectory; and the subdirectory isn't "dtoa" which is required by your code, but e.g. "dtoa-fast-master" for https://github.com/achan001/dtoa-fast/archive/master.zip).

**Comment by mikekaganski** [comment]
> ```
> ...
> dtoa-fast.o: dtoa-fast.c dtoa-aux.c strtod-fast.c strtod-aux.c strtod-gmp.c
> ...
> ```

IIUC you #include dtoa-aux.c and strtod-aux.c into dtoa-fast.c and strtod-fast.c resp., so are they needed as separate units, and shouldn't they be .h instead of .c? And why dtoa-fast.c includes strtod-fast.c? Shouldn't the common defines be moved into an own .h?

**Comment by mikekaganski** [comment]
The MAPM library used here includes dtoa-* files that likely belong here, not to MAPM? And supposedly, MAPM should also be a static library usable from here? So that one could use both libraries in the project, and build MAPM first with the chosen configuration, then build this one (passing the MAPM separate include directory - absent now - to dtoa includes), and then link both libraries with the resulting program?

**Comment by achan001** [comment]
```
IIUC you #include dtoa-aux.c and strtod-aux.c into dtoa-fast.c and strtod-fast.c resp.,
so are they needed as separate units, and shouldn't they be .h instead of .c? 
```
I were never sure what belongs to .c and .h :grin:

The original goal of the project were to ease understanding of David Gay's **dtoa.c**,
a *BIG* file including everything, even arbitrary precision math calculations.

Breaking up the code into units only to keep things simple.
And, this paid off.  I found many dtoa.c bugs, in 2016. https://www.netlib.org/fp/changes

BTW, **BF96_FAST** were David Gay's idea, added to dtoa.c on April 29, 2016
His version had BF96 as default, but can be turned off by #define NO_BF96

I saved his email to me, dated May 5, 2016 (below only a snippet)
```
I've now updated

    http://www.ampl.com/netlib/fp/dtoa.c

to incorporate the above bug fixes and to add my rather different
way of using 64-bit integer arithmetic, using a large array of
powers of 10 in a sort of 96-bit floating-point encoding.  The
resulting dtoa() and strtod() routines are sometimes faster and
sometimes slower than your routines, but usually much faster
than my earlier dtoa.c.  There's also a new dtoa() variant, dtoa_r(),
which adds two trailing arguments, char *buf and size_t blen.  When
buf is not NULL and blen (the size of buf) is large enough, buf is
returned containing the desired string.  I've updated
http://www.ampl.com/netlib/ampl/solvers/printf.c to use dtoa_r()
rather than dtoa().  It's nonstandard in that %.0g gives the mode
0 conversion.  (Many years ago, I urged this upon the C standards
committee, but my suggestion fell on deaf ears.)
```

**Comment by achan001** [comment]
```
And why dtoa-fast.c includes strtod-fast.c?
```
I guess using #include to pull pieces together is not optimal, but I were lazy to create makefiles.
For applications that need the code, I just do #include "dtoa\dtoa-fast.c"

As to _why_ dtoa_fast() require strtod_fast(), think edges.

For rare cases, the edge might require less digits to represent the number.
However, edge might not round-trip back to the same number.  

Example: strtod_fast("7.9999999999999993e+023", NULL) =+0x1.52d02c7e14af6p+79

The edge, "8E23" is much shorter, but can only be used if it round-trip back to above number
Luckily it does, which can be check by their hex-floats.  

+0x1.52d02c7e14af6p+79 = 7.99999999999999932891136E+23
+0x1.52d02c7e14af68p+79 = 8e+23, with half-way-to-even, round-back to above.  

To speedup calculations, dtoa_fast() does not actually convert the 54-bits hex-float.
Instead, it call strtod_fast() to convert "8E23", and check for round-trip.

**Comment by achan001** [comment]
```
The MAPM library used here includes dtoa-* files that likely belong here, not to MAPM?
```

**MAPM libray** also uses dtoa-*.h files for MAPM numbers to IEEE Double (see [mapm_dbl.c](https://github.com/achan001/MAPM-5/blob/master/MAPM/mapm_dbl.c))

Instead of 2 copies of same header files to different projects,  I leave it to MAPM.
This meant MAPM is self-contained, with makefile to create its static library.
(Hopefully, you can just download it, and simply run "make")

On the other hand, **dtoa-fast** is not self-contained, even with the header files moved here.
It require arbitrary precision math package to break ties, for close to half-way case.  

I had setup defaults so that dtoa-fast uses MAPM static library, **libmapm.a**, for this.
(to use **GMP** instead, add #define USE_MAPM 0)

**Comment by mikekaganski** [comment]
> **MAPM libray** also uses dtoa-*.h files for MAPM numbers to IEEE Double (see [mapm_dbl.c](https://github.com/achan001/MAPM-5/blob/master/MAPM/mapm_dbl.c))
> 
> Instead of 2 copies of same header files to different projects, I leave it to MAPM.
> This meant MAPM is self-contained, with makefile to create its static library.
> (Hopefully, you can just download it, and simply run "make")

Understood; but then the files likely should be named mapm_*, and referenced from dtoa as such, to make things clear? Also any dtoa-specific bits should be removed from there (like declaration of functions exported from dtoa)?

**Comment by achan001** [comment]
> Understood; but then the files likely should be named mapm_*, and referenced from dtoa as such, to make things clear? Also any dtoa-specific bits should be removed from there (like declaration of functions exported from dtoa)?

Done.

**DTOA :** added declarations-only dtoa-fast.h (actually copied from your include directory)

**MAPM:** renamed the shared header file as mapm-dtoa.h
