### ISSUE TITLE
Plans to support binary128?

### ISSUE THREAD

**Issue by cesss** [achan001/dtoa-fast#3]
Hi!

I wonder if you have any plans in adapting your code for supporting quad-precision floats (binary128 IEEE 754). I'm using quad-floats with John Hauser's SoftFloat library, but, unfortunately, that library doesn't provide functions for converting floating point values from/to strings, so I'm looking for simple and efficient code for that.

**Comment by achan001** [comment]
Sorry ... no plan to extend for binary128.
